[package]
name = "tauri-plugin-dwrecv"
version = "0.3.0"
authors = ["benditorok"]
description = "Handle Zebra DataWedge broadcast intents to receive and parse barcode data on Android."
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-dwrecv"

[dependencies]
tauri = { version = "2.10.3" }
serde = "1.0.228"
thiserror = "2.0.18"

[build-dependencies]
tauri-plugin = { version = "2.5.4", features = ["build"] }
tauri-build = "2.5.6"
