[package]
name = "tauri-plugin-dwrecv"
version = "0.4.0"
authors = ["benditorok"]
description = "Handle Zebra DataWedge broadcast intents to receive and parse barcode data on Android."
edition = "2024"
rust-version = "1.95.0"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-dwrecv"

[package.metadata.platforms.support]
android = { level = "full", notes = "Receives Android broadcast intents." }
ios = { level = "none" }
windows = { level = "none" }
linux = { level = "none" }
macos = { level = "none" }

[dependencies]
tauri = { version = "2.11.5" }
serde = "1"
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2.6.3", features = ["build"] }
tauri-build = "2.6.3"
